<?xml version="1.0"?>
<package format="3">
  <name>navigation_pkg</name>
  <version>0.0.1</version>
  <description>GPS navigation package</description>
  <maintainer email="user@robot.com">user</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>robot_localization</depend>
  <depend>geographic_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>