#this Dockerfile is used to build an ROS + VNC + package for Ros kit based on ubunut 20.04LTS

FROM ros:humble-ros-core-jammy

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt install --yes \
	sudo cmake g++ libpcl-dev libyaml-cpp-dev \
	libboost-thread-dev libboost-system-dev libboost-filesystem-dev \
	nano ssh git zip distcc ccache \
	libopencv-dev libbullet-dev libspdlog-dev libpcap-dev \
	gcc netcat gettext net-tools libsndfile1 iputils-ping libserial-dev \
	terminator htop libusb-1.0-0 libusb-1.0-0-dev



RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt install -y \
	ros-humble-rviz2 \
	ros-humble-teleop-twist-keyboard \
	ros-humble-tf2 \
	ros-humble-imu-filter-madgwick \
	ros-humble-tf2-eigen \
	ros-humble-pcl-conversions \
	ros-humble-rtcm-msgs \
	ros-humble-nmea-msgs \
	ros-humble-xacro


#Sensors installation: 

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt install -y ros-humble-realsense2-camera

RUN apt-get update && apt-get install -y curl gpg && \
curl -fsSL https://repositories.intel.com/gpu/intel-graphics.key | \
gpg --dearmor -o /usr/share/keyrings/intel-graphics.gpg && \
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] \
https://repositories.intel.com/gpu/ubuntu jammy unified" \
> /etc/apt/sources.list.d/intel-gpu-jammy.list && \
apt-get update && apt-get install -y \
libigdgmm12 \
libigc2=2.11.12-1146~22.04 \
libigdfcl2=2.11.12-1146~22.04 \
intel-opencl-icd=25.18.33578.15-1146~22.04 \
libze-intel-gpu1 \
libze1 \
clinfo \
&& rm -rf /var/lib/apt/lists/*

ARG RENDER_GID=992
RUN groupmod -g ${RENDER_GID} render || groupadd -g ${RENDER_GID} render


######################## ADD NEW DEPENDENCIES JUST ABOVE THIS LINE ###################

RUN apt-get update && apt-get install -y \
	libpython3-dev python3-venv pip python3-catkin-pkg \
	libasio-dev \
	ros-humble-robot-state-publisher \
	ros-humble-joint-state-publisher-gui
RUN /usr/sbin/update-ccache-symlinks
ENV PATH="/usr/lib/ccache:${PATH}"
RUN apt-get update && apt-get install -y \
	libpython3-dev \
	python3-pip \
	python3-venv \
	python3-catkin-pkg-modules

# Install colcon extensions via pip (apt package deprecated in ROS Humble)
RUN pip install -q colcon-common-extensions || echo "Warning: colcon-common-extensions install failed, continuing..."

#_____________________________________________________________________________

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt install -y \
	ros-humble-pcl-ros \
	build-essential         \
    libeigen3-dev           \
    libjsoncpp-dev          \
    libcurl4-openssl-dev
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt install -y \
	ros-humble-gazebo-ros-pkgs \
	ros-humble-control-toolbox \
	ros-humble-controller-manager-msgs \
	ros-humble-diagnostic-updater \ 
	ros-humble-forward-command-controller \ 
	ros-humble-generate-parameter-library \ 
	ros-humble-generate-parameter-library-py \ 
	ros-humble-joint-state-broadcaster \ 
	ros-humble-joint-trajectory-controller \ 
	ros-humble-tf-transformations \
	ros-humble-ros2-controllers \
	ros-humble-ros2-control \
	ros-humble-gazebo-ros2-control \
	ros-humble-robot-localization

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt install -y \ 
ros-humble-navigation2 \
ros-humble-nav2-bringup \
ros-humble-tf2-tools \
ros-humble-tf2-geometry-msgs

# Install SDK lib livox
COPY Livox-SDK2/ /Livox-SDK2
RUN mkdir -p /Livox-SDK2/build
WORKDIR /Livox-SDK2/build
RUN cmake ..
RUN make -j
RUN make install


ARG UID
ARG GID
ARG USER
ARG GROUP
ARG ABSOLUTE_WORKSPACE

RUN echo "$USER ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers
RUN groupadd -g $GID $GROUP

RUN useradd -ms /bin/bash -u $UID -g $GID $USER
RUN adduser $USER dialout
RUN addgroup $USER dialout
RUN adduser $USER video
RUN usermod -a -G video $USER
RUN usermod -a -G render $USER


USER $USER

RUN mkdir -p $ABSOLUTE_WORKSPACE
RUN echo 'alias cm="colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DROS_EDITION=ROS2 -DHUMBLE_ROS=humble"' >> /home/$USER/.bashrc
RUN /bin/bash -c "echo source $ABSOLUTE_WORKSPACE/install/setup.bash >> /home/$USER/.bashrc"

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
