set(_AMENT_PACKAGE_NAME "gr_description")
set(gr_description_VERSION "0.0.0")
set(gr_description_MAINTAINER "hunter_gr <hunter_gr@todo.todo>")
set(gr_description_BUILD_DEPENDS )
set(gr_description_BUILDTOOL_DEPENDS "ament_cmake")
set(gr_description_BUILD_EXPORT_DEPENDS )
set(gr_description_BUILDTOOL_EXPORT_DEPENDS )
set(gr_description_EXEC_DEPENDS "xacro")
set(gr_description_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(gr_description_GROUP_DEPENDS )
set(gr_description_MEMBER_OF_GROUPS )
set(gr_description_DEPRECATED "")
set(gr_description_EXPORT_TAGS)
list(APPEND gr_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
