set(_AMENT_PACKAGE_NAME "gr_bringup")
set(gr_bringup_VERSION "0.0.0")
set(gr_bringup_MAINTAINER "hunter_gr <hunter_gr@todo.todo>")
set(gr_bringup_BUILD_DEPENDS )
set(gr_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(gr_bringup_BUILD_EXPORT_DEPENDS )
set(gr_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(gr_bringup_EXEC_DEPENDS "xacro")
set(gr_bringup_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(gr_bringup_GROUP_DEPENDS )
set(gr_bringup_MEMBER_OF_GROUPS )
set(gr_bringup_DEPRECATED "")
set(gr_bringup_EXPORT_TAGS)
list(APPEND gr_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
